apiVersion: ec2.aws.crossplane.io/v1beta1
kind: NATGateway
metadata:
  name: crossplane-natgateway
spec:
  forProvider:
    region: ap-south-1
    allocationIdRef:
      name: crossplane-eip
    subnetIdRef:
      name: crossplane-public-subnet1
    tags:
      - key: Name
        value: crossplane-natgateway
  providerConfigRef:
    name: default
