apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: crossplane-sg
spec:
  forProvider:
    region: ap-south-1
    vpcIdRef:
      name: crossplane-vpc  
    groupName: crossplane-group-sg
    description: security-group
    egress:
      - fromPort: 0
        ipProtocol: "-1"
        ipRanges:
          - cidrIp: "0.0.0.0/0"
    ingress:
      - fromPort: 22
        toPort: 22
        ipProtocol: tcp
        ipRanges:
          - cidrIp: "0.0.0.0/0"
    tags:
      - key: Name
        value: crossplane-sg
  providerConfigRef:
    name: default
